#ifndef COMMAND_RETURN_LIST_H
#define COMMAND_RETURN_LIST_H

#define COMMAND_RETURN_NOT_FOUND -3
#define COMMAND_RETURN_RETRY -2
#define COMMAND_RETURN_EXIT -1
#define COMMAND_RETURN_SUCCESS 0

#endif