#ifndef COMMAND_RETURN_LIST_H
#define COMMAND_RETURN_LIST_H

#define COMMAND_RETURN_SUCCESS 0
#define COMMAND_RETURN_COMMENT 1
#define COMMAND_RETURN_EXIT 2
#define COMMAND_RETURN_RETRY 3
#define COMMAND_RETURN_EXEC_ERR 4

#define COMMAND_RETURN_NOT_FOUND 127
#define COMMAND_RETURN_INTERNAL_CMD 254

#endif
